travis:
  secure:
    BINSTAR_TOKEN: vCeVZ0krV99EfQjWeNl8zPc7VKTfKryWxlt87OMXWN64UxK5LvHgw4UTlJOazIeLwxVcake0HaaY/1PayVcnnfHWNyZQ8nDiAgf4KYUDGAPNjRcA8LxWPABb9gXfZYZyr8Ea19rNza+6/VksggTpGcOSzoRU57WZuVpqOdZFZWpOP1yOG3WlbskRWFaknzi/pZONVWNuPXsNWzRwPMtViy1nn+AMMhX3PIxKC6Bw1q6cxGn4muB1eL9+xfzIZB2KITbYycf3Wfbgliwuw9LGwuuhGBufsIOPfR3ZddyP/KaYQvDwBMPQQrgUOaLb5pgP4TBdvvBgbNj0+pZuslDjsWDmrJfQ08X8eROD3oigXA+6oVyb5L8PuY2c2sU6m281KWU/oBYjwZG/OJbt0nKkVSGFx6gIMn51IOE54aP545faZ0wc5pFgZEzSdeox2cuReqsdyyt5/CgeCCr22957jO5Oeg9Miyb64RgTK0xyFBtb4HJVv+1ExIE4TSqcUaeuMF45+IUGvSw39mZVuZtjXD7EPsWfu+mnjVJeNz5wFiBCov3VMH/6R0SCkcmPdbxwyMraTXGl9uhpO5MoaKVwti8LfbzkqmkRaiumeKEkDMy2ZAFci8qM1x6S8q0/gOfPRPUfIyppU0PxwTJAtXnnpZrQ++PvYkCSJ0xqxgE+sc4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
