travis:
  secure:
    BINSTAR_TOKEN: q+cH7JlvQR4VtI12mPTZ+5+bo+3lbiW7a+POwfqqQt71MOyxr0tJXwxvZ/hZUbyJ7UOJGMd7E112NRtRySahfeOApfs21XvkOvkgZdppYn6upZfqdSTBIOJjUf44xGZLfxdf8PtoduWgSTrdbbwa5/IHHGFnCvFSYXwPLovoJrTwBnaMVtsft0jkggmXmLNnsZrZJTTh2JmzqvyFbsG4IXkfu6NJtsVf2/CDQOKYERDHRdYBWZXVIsh6JkgV/eTEJhiiRSfrLS8/L2Ly4yN31SY9dkFI2Kj1ogPZCNooRL1E+H9a2lHFGT8e01Ws59BRTCkqksQ7ighyLwim/lNpGGq+7Lotgvkcxc+joi7PLQ55AbQIlkgpKJ+RgjUdI5vM9Ngw+5/alKCtlp8gVMjFtI9HpACsxlUEuusuYgVVX6YxDPY+TP5RAUFY86W0VSKXrSqeQz+4zD/DZVXmxW+PK8F4B7wBZAWLQCAKyruCYjTkg1VPh92wHVWgujlB0d3aH8Z9C26S1VXOqpCMyLtOLiuk18a8cH/DXkeedoczXMmaTogeVCRhp87sIVKWEvuWCJ75Xn0i6R+RIFFMc5cMLiwwWdFECQwvEVI/AaZk2o0yZYJE5B+8HtVIZNFMjcQNfZ0rbtATFbAhnx8kPDKQBRyZdjV01zKULjpMdI4g328=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
